#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_ROOT = REPO_ROOT / "docs"
@dataclass(frozen=True)
class DocMeta:
    title: str | None
    status: str | None


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def parse_doc_meta(path: Path) -> DocMeta:
    title = None
    status = None
    lines = read_text(path).splitlines()
    for index, line in enumerate(lines[:60]):
        stripped = line.strip()
        if title is None and stripped.startswith("# "):
            title = stripped[2:].strip()
        if status is None and stripped.lower().startswith("status:"):
            status = stripped.split(":", 1)[1].strip()
        elif status is None and stripped in {"## Status", "### Status"}:
            for follow in lines[index + 1 : index + 8]:
                follow_stripped = follow.strip()
                if not follow_stripped:
                    continue
                if follow_stripped.startswith("#"):
                    break
                status = follow_stripped.rstrip(".")
                break
        if title is not None and status is not None:
            break
    return DocMeta(title=title, status=status)


def format_doc_bullet(base_dir: Path, doc_path: Path) -> str:
    rel = doc_path.relative_to(base_dir).as_posix()
    meta = parse_doc_meta(doc_path)
    parts = [f"- [{doc_path.name}](./{rel})"]
    if meta.title and meta.title != doc_path.name:
        parts.append(meta.title)
    if meta.status:
        parts.append(f"`Status: {meta.status}`")
    return " — ".join(parts)


def build_root_inventory() -> str:
    subdirs = ["contracts", "designs", "specs", "roadmaps", "adrs", "archived"]
    lines = [
        "## Generated Inventory",
        "",
        "_This section is generated by `scripts/update_doc_indices.py`. Do not edit it by hand._",
        "",
        "### Subdirectories",
        "",
    ]
    for name in subdirs:
        directory = DOCS_ROOT / name
        count = len(
            [path for path in sorted(directory.glob("*.md")) if path.name != "README.md"]
        )
        lines.append(
            f"- [{name}/README.md](./{name}/README.md) — {count} indexed markdown document"
            f"{'' if count == 1 else 's'}"
        )
    top_level_docs = [
        path
        for path in sorted(DOCS_ROOT.glob("*.md"))
        if path.name != "README.md"
    ]
    lines.extend(["", "### Top-Level Docs", ""])
    for doc_path in top_level_docs:
        lines.append(format_doc_bullet(DOCS_ROOT, doc_path))
    return "\n".join(lines)


def build_directory_inventory(directory: Path, heading: str) -> str:
    files = [path for path in sorted(directory.glob("*.md")) if path.name != "README.md"]
    lines = [
        heading,
        "",
        "_This section is generated by `scripts/update_doc_indices.py`. Do not edit it by hand._",
        "",
    ]
    if not files:
        lines.append("- No indexed markdown documents.")
        return "\n".join(lines)
    for path in files:
        lines.append(format_doc_bullet(directory, path))
    return "\n".join(lines)


def render_replaced_block(readme_path: Path, block_name: str, rendered: str) -> str:
    text = read_text(readme_path)
    begin = f"<!-- BEGIN GENERATED INDEX: {block_name} -->"
    end = f"<!-- END GENERATED INDEX: {block_name} -->"
    before, found_begin, remainder = text.partition(begin)
    middle, found_end, after = remainder.partition(end)
    if not found_begin or not found_end:
        raise RuntimeError(f"missing generated block markers for {block_name} in {readme_path}")
    replacement = f"{begin}\n{rendered}\n{end}"
    return before + replacement + after


def update_indices(check: bool) -> int:
    targets = [
        (
            DOCS_ROOT / "README.md",
            "docs-root",
            build_root_inventory(),
        ),
        (
            DOCS_ROOT / "contracts" / "README.md",
            "docs-contracts",
            build_directory_inventory(DOCS_ROOT / "contracts", "## Generated Contract Inventory"),
        ),
        (
            DOCS_ROOT / "designs" / "README.md",
            "docs-designs",
            build_directory_inventory(DOCS_ROOT / "designs", "## Generated Design Inventory"),
        ),
        (
            DOCS_ROOT / "specs" / "README.md",
            "docs-specs",
            build_directory_inventory(DOCS_ROOT / "specs", "## Generated Spec Inventory"),
        ),
        (
            DOCS_ROOT / "roadmaps" / "README.md",
            "docs-roadmaps",
            build_directory_inventory(DOCS_ROOT / "roadmaps", "## Generated Roadmap Inventory"),
        ),
        (
            DOCS_ROOT / "adrs" / "README.md",
            "docs-adrs",
            build_directory_inventory(DOCS_ROOT / "adrs", "## Generated ADR Inventory"),
        ),
        (
            DOCS_ROOT / "archived" / "README.md",
            "docs-archived",
            build_directory_inventory(DOCS_ROOT / "archived", "## Generated Archived Inventory"),
        ),
    ]

    changed: list[Path] = []
    for readme_path, block_name, rendered in targets:
        original = read_text(readme_path)
        updated = render_replaced_block(readme_path, block_name, rendered)
        if updated != original:
            changed.append(readme_path)
            if not check:
                write_text(readme_path, updated)

    if check and changed:
        for path in changed:
            print(path.relative_to(REPO_ROOT).as_posix())
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if indices are stale")
    args = parser.parse_args()
    return update_indices(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
